### ISSUE TITLE
When using nextloud 13 the setting for selecting the cron job is not available, i assume the "sidecar" still does its job?

### ISSUE THREAD

**Issue by IvanTurgenev** [crazy-max/docker-nextcloud#3]
ps thanks man great project, easy and not confusing, nginx + sqlite + alpine my small vps thanks you and i do too, need something lightweight only for personal use, out of curiosity why cant the nginx inside the image also do the proxing and certs? isnt it rebundant nginx+ traefik?

**Comment by IvanTurgenev** [comment]
ps thanks man great project, nginx + sqlite + alpine my small vps thanks and i do too, out of curiosity why cant the nginx inside the image also do the proxing and certs? isnt it rebundant nginx+ traefik?

**Comment by crazy-max** [comment]
Hi @IvanTurgenev, Traefik does not ([yet?](https://github.com/containous/traefik/issues/753)) support fastcgi that's why.
I like to separate reverse proxy (traefik) and services (nextcloud, dokuwiki, matomo, librenms, etc...) and only expose one container. But also Traefik is really nice to handle Let's encrypt certificates :)

**Comment by crazy-max** [comment]
You seem to have mix the title and content of this issue. Please create a new issue for this :

```When using nextloud 13 the setting for selecting the cron job is not available, i assume the "sidecar" still does its job?```

Thx
